// <auto-generated />
namespace ZeonEcommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview6-19304-03")]
    public sealed partial class OrderDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201910220610072_OrderDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
